export const CHANGE_STATE = 'CHANGE_STATE';
export const SEARCH_FOR_PLAYER = 'SEARCH_FOR_PLAYER';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
export const UPDATE_PLAYER_CHARACTERS = 'UPDATE_PLAYER_CHARACTERS';